# Generated by Django 5.2.1 on 2025-06-25 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98328583-494e-468d-9d15-3a9fb9e313bc'), primary_key=True, serialize=False, unique=True),
        ),
    ]
