# Generated by Django 5.2.1 on 2025-07-04 23:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('delivery_time', models.DurationField(default=datetime.timedelta(days=3), help_text='Estimated delivery time in hours')),
                ('is_active', models.BooleanField(default=True)),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='laundryservice.garment')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='laundryservice.laundryservice')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicetypes', to='laundryservice.servicetype')),
            ],
            options={
                'unique_together': {('service_name', 'service_type', 'service_item')},
            },
        ),
    ]
