# Generated by Django 5.2.1 on 2025-07-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundryservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepricing',
            old_name='delivery_time',
            new_name='duration',
        ),
    ]
